### ISSUE TITLE
When importing from original version of Slick RSS, refreshing of feeds stop at 17.

### ISSUE THREAD

**Issue by alatnet** [gandf/slick-rss#22]
So, im importing my feeds from the original version of Slick RSS and i keep getting a problem with it stopping at 17 feed updates.
Anything after it just will not refresh or update it's information.

here's the feeds that im using (78 in total, some just return 404 since they are defunct, havent gotten around to cleaning it up):
`<?xml version="1.0" encoding="ISO-8859-1"?><opml version="2.0"><head><title>Slick RSS OPML Export</title></head><body><outline type="rss" text="Sexless Friend" xmlUrl="http://www.mangahere.co/rss/sexless_friend.xml" group=""/><outline type="rss" text="deviantART: gallery:meganekkochaser/37582820" xmlUrl="http://backend.deviantart.com/rss.xml?q=gallery%3Ameganekkochaser%2F37582820&amp;type=deviation" group=""/><outline type="rss" text="Comics – RandoWis" xmlUrl="http://randowis.com/feed/" group=""/><outline type="rss" text="kukuruyo" xmlUrl="http://kukuruyo.com/feed/" group=""/><outline type="rss" text="Dude and Death : The Origins" xmlUrl="http://tapastic.com/rss/series/24884" group=""/><outline type="rss" text="The Adventures of Business Cat" xmlUrl="http://www.businesscat.happyjar.com/feed/" group=""/><outline type="rss" text="Dragon's Burn" xmlUrl="http://dragonsburn.tumblr.com/rss" group=""/><outline type="rss" text="4-Panel Life" xmlUrl="http://tapastic.com/rss/series/6107" group=""/><outline type="rss" text="The Escapist : Critical Miss" xmlUrl="https://www.escapistmagazine.com/v2/feed/" group=""/><outline type="rss" text="the GaMERCaT" xmlUrl="http://tapastic.com/rss/series/526" group=""/><outline type="rss" text="Fisheye Placebo" xmlUrl="http://tapastic.com/rss/series/347" group=""/><outline type="rss" text="deviantART: gallery:yuumei/42604730" xmlUrl="http://backend.deviantart.com/rss.xml?q=gallery%3Ayuumei%2F42604730&amp;type=deviation" group=""/><outline type="rss" text="SugarStars" xmlUrl="http://tapastic.com/rss/series/262" group=""/><outline type="rss" text="Ribon" xmlUrl="http://tapastic.com/rss/series/313" group=""/><outline type="rss" text="Megatokyo Comics" xmlUrl="http://megatokyo.com/rss/strips.xml" group=""/><outline type="rss" text="Charlie Sheen" xmlUrl="http://charliesheencomic.com/feed/" group=""/><outline type="rss" text="SPACE BASTARDS" xmlUrl="http://space-bastards.com/feed/" group=""/><outline type="rss" text="Gone With the Blastwave" xmlUrl="http://www.blastwave-comic.com/rss/blastwave.xml" group=""/><outline type="rss" text="Super Effective" xmlUrl="http://www.vgcats.com/super/se.rdf.xml" group=""/><outline type="rss" text="Chaos Life" xmlUrl="http://chaoslife.findchaos.com/feed" group=""/><outline type="rss" text="The GaMERCaT" xmlUrl="http://www.thegamercat.com/feed/" group=""/><outline type="rss" text="FindChaos" xmlUrl="http://www.findchaos.com/feed" group=""/><outline type="rss" text="BladeKitten.com - Most Recent Blade Kitten Comics" xmlUrl="http://feeds2.feedburner.com/bladekittencomics" group=""/><outline type="rss" text="Head Trip" xmlUrl="http://headtrip.keenspot.com/rss.xml" group=""/><outline type="rss" text="Ubunchu!" xmlUrl="http://divajutta.com/doctormo/ubunchu/feed.rss" group=""/><outline type="rss" text="Ctrl+Alt+Del" xmlUrl="http://www.cad-comic.com/rss/rss.xml" group=""/><outline type="rss" text="Aki-chan's Life" xmlUrl="http://www.jimmys-desktop.de/aki.php?rss" group=""/><outline type="rss" text="Manly Guys Doing Manly Things" xmlUrl="http://thepunchlineismachismo.com/feed" group=""/><outline type="rss" text="EVA-303 Updates" xmlUrl="http://eva303.smackjeeves.com/rss/" group=""/><outline type="rss" text="JESUS CHRIST - IN THE NAME OF THE GUN" xmlUrl="http://jesuschriststory.com/feed/" group=""/><outline type="rss" text="The Setup Wizard" xmlUrl="http://thesetupwizard.tumblr.com/rss" group=""/><outline type="rss" text="Digimon World Re:Digitized Translation" xmlUrl="https://digimonworldre.wordpress.com/feed/" group=""/><outline type="rss" text="The World" xmlUrl="http://www.coldbird.net/feed/" group=""/><outline type="rss" text="DevZone Topic Subscriptions" xmlUrl="https://devtalk.nvidia.com/rss/feed/tL%2FrW%2BdWpEX7UHUtLNDPsKmaQKaSP6w8udKaQLjmk0A%3D" group=""/><outline type="rss" text="Did You Know Gaming?" xmlUrl="http://didyouknowgaming.com/rss" group=""/><outline type="rss" text="PSO-World.com - The World's Largest Phantasy Star Community - PS Universe, Portable, Zero, Online" xmlUrl="http://www.pso-world.com/rss.xml" group=""/><outline type="rss" text="Break The Bank Habit" xmlUrl="http://brightstarcu.wordpress.com/feed/" group=""/><outline type="rss" text="Vocaloidism" xmlUrl="http://www.vocaloidism.com/feed/" group=""/><outline type="rss" text="PSO2 NA Blog" xmlUrl="http://bumped.org/pso2na/feed/" group=""/><outline type="rss" text="Phantasy Star Fan Blog" xmlUrl="http://www.bumped.org/psublog/feed/" group=""/><outline type="rss" text="Xenoaisam Website" xmlUrl="http://xenoaisam.com/feed/" group=""/><outline type="rss" text="Mary Cagle Let's Speak English" xmlUrl="http://www.marycagle.com/rss.php" group=""/><outline type="rss" text="Isekai Soul-Cyborg Translations » Feed" xmlUrl="https://isekaicyborg.wordpress.com/feed/" group=""/><outline type="rss" text="The Hazards of Being a Main Character" xmlUrl="https://tapastic.com/rss/series/12603" group=""/><outline type="rss" text="Please Be Merciful" xmlUrl="https://tapastic.com/rss/series/42550" group=""/><outline type="rss" text="The Gamer" xmlUrl="https://www.webtoons.com/en/action/the-gamer/rss?title_no=88" group=""/><outline type="rss" text="The Pigeon Gazette" xmlUrl="https://tapas.io/rss/series/8207" group=""/><outline type="rss" text="Genjicat" xmlUrl="https://tapas.io/rss/series/68320" group=""/><outline type="rss" text="mikiko mini comics" xmlUrl="https://tapas.io/rss/series/4668" group=""/><outline type="rss" text="Soggy Cardboard" xmlUrl="http://www.soggycardboard.com/?feed=rss2" group=""/><outline type="rss" text="Surfacage [and the world will turn to ash]" xmlUrl="http://www.surfacage.net/rss" group=""/><outline type="rss" text="DBZ - The Girl Next Door" xmlUrl="http://the-girl-next-door.smackjeeves.com/rss/" group=""/><outline type="rss" text="Erma" xmlUrl="https://tapas.io/rss/series/23931" group=""/><outline type="rss" text="Watashu" xmlUrl="https://tapas.io/rss/series/33746" group=""/><outline type="rss" text="Coon Comic" xmlUrl="https://tapas.io/rss/series/53898" group=""/><outline type="rss" text="Customer Service Wolf" xmlUrl="http://customerservicewolf.com/rss" group=""/><outline type="rss" text="Crawling Dreams" xmlUrl="https://tapas.io/rss/series/91644" group=""/><outline type="rss" text="The Crawling City" xmlUrl="https://tapas.io/rss/series/42485" group=""/><outline type="rss" text="The Elf is a Freeloader" xmlUrl="https://www.euricette.com/category/series/the-elf-is-a-freeloader/feed/" group=""/><outline type="rss" text="dijoninpieces" xmlUrl="https://dijoninpieces.wordpress.com/feed/" group=""/><outline type="rss" text="Omega Harem Translations » Feed" xmlUrl="https://omegaharem.wordpress.com/feed/" group=""/><outline type="rss" text="Fmgandalf translations » Feed" xmlUrl="https://fmgandalf.wordpress.com/feed/" group=""/><outline type="rss" text="dijoninpieces » I Was a Sword When I Reincarnated Category Feed" xmlUrl="https://dijoninpieces.wordpress.com/category/i-was-a-sword-when-i-reincarnated/feed/" group=""/><outline type="rss" text="“A Tale of Two Rulers”" xmlUrl="http://figmentforms.tumblr.com/rss" group=""/><outline type="rss" text="Haruka" xmlUrl="https://www.webtoons.com/en/challenge/haruka/rss?title_no=141998" group=""/><outline type="rss" text="Reincarnated As A Dragons Egg" xmlUrl="https://dsrealmtranslations.com/category/reincarnated-as-a-dragons-egg/feed/" group=""/><outline type="rss" text="Negative Frames" xmlUrl="https://tapas.io/rss/series/88299" group=""/><outline type="rss" text="Stalker x Stalker" xmlUrl="https://www.webtoons.com/en/challenge/stalker-x-stalker/rss?title_no=245662" group=""/><outline type="rss" text="Future Sound" xmlUrl="https://tapas.io/rss/series/124387" group=""/><outline type="rss" text="Edd Lai's Stories" xmlUrl="https://www.webtoons.com/en/challenge/edd-lais-stories/rss?title_no=301213" group=""/><outline type="rss" text="Deathsitter" xmlUrl="https://www.webtoons.com/en/challenge/deathsitter/rss?title_no=293285" group=""/><outline type="rss" text="London Vampire" xmlUrl="https://www.webtoons.com/en/challenge/london-vampire/rss?title_no=70817" group=""/><outline type="rss" text="Magnolia Online" xmlUrl="https://www.webtoons.com/en/challenge/magnolia-online/rss?title_no=56485" group=""/><outline type="rss" text="Clinic of Horrors" xmlUrl="https://www.webtoons.com/en/challenge/clinic-of-horrors/rss?title_no=274661" group=""/><outline type="rss" text="My Succubus Girlfriend" xmlUrl="https://www.webtoons.com/en/challenge/my-succubus-girlfriend/rss?title_no=116486" group=""/><outline type="rss" text="Vampire Gamer" xmlUrl="https://www.webtoons.com/en/challenge/vampire-gamer/rss?title_no=388506" group=""/><outline type="rss" text="system32comics" xmlUrl="https://www.webtoons.com/en/challenge/system32comics/rss?title_no=235074" group=""/><outline type="rss" text="The Bikini Bottom Horror" xmlUrl="https://stillinthesimulation.com/untitled-comic/feed/" group=""/></body></opml>`

**Comment by gandf** [comment]
It's an error in RSS feed. Some item have no date.
I will fix this issue.

**Comment by gandf** [comment]
Fixed by commit d0c279c6c9ceab69a47c86705c6282f039a81e8f
