### ISSUE TITLE
Add support for <title type="html">

### ISSUE THREAD

**Issue by SpaceBison** [gandf/slick-rss#23]
I'm subscribed to a feed that published HTML-type titles with embedded links:

```xml
<title type="html">&lt;a href="..." class="activity-item-user activity-item-author">...&lt;/a> logged '0.25d' on &lt;a href="...">...&lt;/a>
  </title>
```

SlickRSS renders it as text, leaving HTML tags unparsed, causing the title to be almost unreadable.

**Comment by gandf** [comment]
Fixed in 3.7.
