### ISSUE TITLE
Feed order is incorrect sometimes

### ISSUE THREAD

**Issue by Qrox** [gandf/slick-rss#44]
Some RSS feeds do not include a publication date in the items ([example](https://rss.webofknowledge.com/rss?e=3298213ce6d9aba0&c=732024a2a4db8761e31d720f2fc6e6da)), which is allowed by the [specification](https://validator.w3.org/feed/docs/rss2.html#optionalChannelElements), but in Slick RSS the order of new items is incorrect for this kind of feeds.

According to the following code,

https://github.com/gandf/slick-rss/blob/15347a84ad88a514ea6ce396f96fc10515bb0804/background.js#L955-L960

The order when there is date information is the time difference between the item date and a reference date, but the order when there is no date information is the reference date. This logic seems wrong to me.

I think it should either use the channel date and, if there is no channel date, the access date for the order, so items without date information can be displayed in the order they are published.

**Comment by Qrox** [comment]
Yes, I included one in the OP, [at this link](https://rss.webofknowledge.com/rss?e=3298213ce6d9aba0&c=732024a2a4db8761e31d720f2fc6e6da).

**Comment by gandf** [comment]
Closed by commit 561a41e
