### ISSUE TITLE
Option: "Show all feeds in one" 

### ISSUE THREAD

**Issue by angomania** [gandf/slick-rss#53]
The Option "Show all feeds in one" is only working with feeds in groups.
If a feed is in no group it would not display in "All Feeds"

Does it have to be like this?

**Comment by gandf** [comment]
Thank you for your feedback.
I'll see where the bug is and fix it because it's a bug.

But it's going to take me a bit of time because I don't have much time between now and the end of the month.

I hope to have made this fix and requested deployment by July 10 at the latest.

**Comment by gandf** [comment]
Fixed by commit c759387
